#!/bin/sh

export PATH="${PATH}:usr/bin:/$HOME/.local/bin:$HOME/.local/scripts:$HOME/.local/bin/scripts:$HOME/.local/bin/Applications:$HOME/.local/bin/VMs:$HOME/.local/bin/network"
#export PATH="${PATH}:usr/bin:/$HOME/.local/bin:$HOME/.local/scripts:$HOME/.local/bin/*"

export EDITOR=nvim                  
export VISUAL=nvim
export TERMINAL=alacritty               
#export TERMINAL=kitty
#export TERM=xterm-kitty
export PAGER=less
export READER=zathura
export BROWSER=brave
export MANPAGER='nvim +Man!'
export MANWIDTH=999

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export _ZO_DATA_DIR=$XDG_DATA_HOME/zsh/
export _ZO_ECHO=1   # z will print matched directory before navigating to it

export FONTCONFIG_PATH=/etc/fonts
export QT_QPA_PLATFORMTHEME=qt5ct
export GNUPGHOME=$HOME/.config/gnupg
export RANGER_LOAD_DEFAULT_RC=FALSE     # Prevent duplicate loading of Ranger config

# LIBVIRT DEFAULT URI
# See: https://serverfault.com/questions/803283/how-do-i-list-virsh-networks-without-sudo
# See: https://libvirt.org/uri.html#URI_default
export LIBVIRT_DEFAULT_URI=qemu:///system

# --------------------------------------------------------------------------------
# cs50.h variables as recommended by https://cs50.readthedocs.io/libraries/cs50/c/
# --------------------------------------------------------------------------------
export CC="clang"
# export CC="gcc"
export CFLAGS="-fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow"

export LDLIBS="-lcrypt -lcs50 -lm"
export LD_LIBRARY_PATH=/usr/local/lib	#cs50 rec. path
#export LD_LIBRARY_PATH=/usr/lib		# 

# additional failsafes:
export LIBRARY_PATH=/usr/local/lib
export C_INCLUDE_PATH=/usr/local/include

