vim.g.vimwiki_list = {{path = '$HOME/.local/share/vimwiki', syntax = 'markdown', ext = '.md'}}
-- require('vimwiki').setup{
  --  config = function()
--        vim.g.vimwiki_list = {
--            {
--                path = '$HOME/.local/share/vimwiki',
--                syntax = 'markdown',
--                ext = '.md',
--            }
--        }
 --   end
--}
--require('vimwiki').setup{
--    config = function()
--        vim.g.vimwiki_list = {
--            {
--                path = '$HOME/wiki',
--                syntax = 'markdown',
--                ext = '.md',
--            }
--        }
--    end
--}
