#!/bin/bash
#
#~/.config/xorg/Xstartup
#
# Programs to start when x-server starts


nm-applet &
udiskie -t &    # (with system tray icon)
picom --experimental-backends &
lxsession &
dunst &
xbindkeys &
#pasystray &	# after lxsession was actually operating, this systray app (along with syncthing) started automatically

# pkill firewall-applet
killfireapplet &
